name: Get latest Australian Payphones Data
on:
  schedule:
    - cron: "0 0 * * *"
  # push:
  #   branches: [ master ]

jobs:
  get-latest:
    runs-on: ubuntu-latest
    name: get latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run get-latest
        env:
          COMMIT_NAME: ${{ secrets.COMMIT_NAME }}
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
